# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.srcs/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3.xci
# IP: The module: 'PmodDemo_auto_ds_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.gen/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodDemo_auto_ds_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.gen/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodDemo_auto_ds_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.srcs/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3.xci
# IP: The module: 'PmodDemo_auto_ds_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.gen/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodDemo_auto_ds_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.gen/sources_1/bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'PmodDemo_auto_ds_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
