# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/header.xdc

# Block Designs: bd/PmodDemo/PmodDemo.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo || ORIG_REF_NAME==PmodDemo} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_mig_7series_0_0/PmodDemo_mig_7series_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_mig_7series_0_0 || ORIG_REF_NAME==PmodDemo_mig_7series_0_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_clk_wiz_0_0/PmodDemo_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_clk_wiz_0_0 || ORIG_REF_NAME==PmodDemo_clk_wiz_0_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_reset_inv_0_0/PmodDemo_reset_inv_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_reset_inv_0_0 || ORIG_REF_NAME==PmodDemo_reset_inv_0_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_microblaze_0_0/PmodDemo_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_microblaze_0_0 || ORIG_REF_NAME==PmodDemo_microblaze_0_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_dlmb_v10_0/PmodDemo_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_dlmb_v10_0 || ORIG_REF_NAME==PmodDemo_dlmb_v10_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_ilmb_v10_0/PmodDemo_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_ilmb_v10_0 || ORIG_REF_NAME==PmodDemo_ilmb_v10_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_dlmb_bram_if_cntlr_0/PmodDemo_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==PmodDemo_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_ilmb_bram_if_cntlr_0/PmodDemo_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==PmodDemo_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_lmb_bram_0/PmodDemo_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_lmb_bram_0 || ORIG_REF_NAME==PmodDemo_lmb_bram_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_xbar_0/PmodDemo_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_xbar_0 || ORIG_REF_NAME==PmodDemo_xbar_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_pc_4/PmodDemo_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_pc_4 || ORIG_REF_NAME==PmodDemo_auto_pc_4} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_us_0/PmodDemo_auto_us_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_us_0 || ORIG_REF_NAME==PmodDemo_auto_us_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_us_1/PmodDemo_auto_us_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_us_1 || ORIG_REF_NAME==PmodDemo_auto_us_1} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_us_2/PmodDemo_auto_us_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_us_2 || ORIG_REF_NAME==PmodDemo_auto_us_2} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_ds_0/PmodDemo_auto_ds_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_ds_0 || ORIG_REF_NAME==PmodDemo_auto_ds_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_pc_0/PmodDemo_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_pc_0 || ORIG_REF_NAME==PmodDemo_auto_pc_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_cc_0/PmodDemo_auto_cc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_cc_0 || ORIG_REF_NAME==PmodDemo_auto_cc_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_ds_1/PmodDemo_auto_ds_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_ds_1 || ORIG_REF_NAME==PmodDemo_auto_ds_1} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_pc_1/PmodDemo_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_pc_1 || ORIG_REF_NAME==PmodDemo_auto_pc_1} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_ds_2/PmodDemo_auto_ds_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_ds_2 || ORIG_REF_NAME==PmodDemo_auto_ds_2} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_pc_2/PmodDemo_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_pc_2 || ORIG_REF_NAME==PmodDemo_auto_pc_2} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_ds_3/PmodDemo_auto_ds_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_ds_3 || ORIG_REF_NAME==PmodDemo_auto_ds_3} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_auto_pc_3/PmodDemo_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_auto_pc_3 || ORIG_REF_NAME==PmodDemo_auto_pc_3} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_microblaze_0_axi_periph_0/PmodDemo_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_microblaze_0_axi_periph_0 || ORIG_REF_NAME==PmodDemo_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_microblaze_0_axi_intc_0/PmodDemo_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_microblaze_0_axi_intc_0 || ORIG_REF_NAME==PmodDemo_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_microblaze_0_xlconcat_0/PmodDemo_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_microblaze_0_xlconcat_0 || ORIG_REF_NAME==PmodDemo_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_mdm_1_0/PmodDemo_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_mdm_1_0 || ORIG_REF_NAME==PmodDemo_mdm_1_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_rst_clk_wiz_0_100M_0/PmodDemo_rst_clk_wiz_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_rst_clk_wiz_0_100M_0 || ORIG_REF_NAME==PmodDemo_rst_clk_wiz_0_100M_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_rst_mig_7series_0_83M_0/PmodDemo_rst_mig_7series_0_83M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_rst_mig_7series_0_83M_0 || ORIG_REF_NAME==PmodDemo_rst_mig_7series_0_83M_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_axi_uartlite_0_0/PmodDemo_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_axi_uartlite_0_0 || ORIG_REF_NAME==PmodDemo_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/PmodDemo/ip/PmodDemo_PmodSD_0_0/PmodDemo_PmodSD_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==PmodDemo_PmodSD_0_0 || ORIG_REF_NAME==PmodDemo_PmodSD_0_0} -quiet] -quiet

# XDC: c:/Users/micro/OneDrive/Documents/GitHub/FPGA-Projects/Programs/microBlaze/microBlaze.gen/sources_1/bd/PmodDemo/PmodDemo_ooc.xdc
